### ISSUE TITLE
[v0.4] checklist to migrate to pytorch 0.4.0

### ISSUE THREAD

**Issue by whr94621** [whr94621/NJUNMT-pytorch#17]
I list all the places need to be modified. Feel free to add below.

- [x] Replace ```.data```  with ```.detach()```. (#16, c3636b0d6c5ae75fd44537d704122bc3537ab79c)
- [x] Update pytorch requirement and v0.3 branch in ```README.md```. (2bbae4a9aad25d3b9dd182c0f859b68f888ae407)
- [x] Use ```set_grad_enabled```, ```enable_grad```, ```no_grad``` as context-manager. (c3636b0d6c5ae75fd44537d704122bc3537ab79c)
- [x] Use official ```LayerNorm``` instead. (247b3a381ae97802628cdc6168ab975b878dd3c2)
- [x] Use ```clip_grad_norm_``` instead. (247b3a381ae97802628cdc6168ab975b878dd3c2)
~~Fix ```shard``` in v0.4~~

**Comment by whr94621** [comment]
Unfortunately, ```shard``` mechanism maybe not effective in PyTorch 0.4 version.
